# Generated by Django 6.0.5 on 2026-05-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_diff', models.IntegerField()),
                ('mismo_deporte', models.IntegerField()),
                ('misma_musica', models.IntegerField()),
                ('misma_mascota', models.IntegerField()),
                ('misma_personalidad', models.IntegerField()),
                ('match', models.IntegerField()),
            ],
        ),
    ]
